# Numpy

### Numpy is a fundamental library for scientific computing in python. It provides support for array and matrices.

In [1]:
import numpy as np

#creating array using numpy
##creating 1D array
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [2]:
#converting 1-D array to 2-D array
arr2 = np.array([1,2,3,4])
arr2.reshape(1,4)

array([[1, 2, 3, 4]])

In [5]:
#2rows

arr2 = np.array([[1,2,3,4], [2,4,6,8]])
print(arr2)
print(arr2.shape)

#it's a 2-D array

[[1 2 3 4]
 [2 4 6 8]]
(2, 4)


In [8]:
#to create array by function
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
#creating array with given rows and columns and all elements will be one
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
#to create Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of Dimension: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Datatype: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimension:  2
Size (number of elements):  6
Datatype:  int64
Item size (in bytes):  8


In [14]:
### Numpy Vectorizedd operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

##addition
print("Addition: ", arr1 + arr2)

#Subtraction
print("Subtraction: ", arr1 - arr2)

##Multiplication
print("Multiplication: ", arr1 * arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]


In [20]:
arr4 = ([2,3,4,5,6])

print("\nA. ", np.sqrt(arr4))

print("\nB. ", np.exp(arr4))

print("\nC. ", np.sin(arr4))

print("\nD. ", np.log(arr4))


A.  [1.41421356 1.73205081 2.         2.23606798 2.44948974]

B.  [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]

C.  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]

D.  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


# Slicing and Indexing

In [21]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
## Accessing 1
print(arr[0][0])

1


In [23]:
## Accessing 7, 8, 11, 12

print(arr[1: , 2: ]) #start from 1st row and go till the end, and start from 2nd column go till the end


[[ 7  8]
 [11 12]]


In [25]:
## Accessing 3, 4, 7, 8

print(arr[0:2,  2:])  # Start 0th row to 1st row(exclude 2) start from 2nd column to end column


[[3 4]
 [7 8]]


In [29]:
## Accessing 6, 7, 10, 11

print(arr[1: , 1:3])

[[ 6  7]
 [10 11]]
